[package]
name = "ipss"
version = "0.1.1"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = { path = "cli" }
file_explorer = { path = "file_explorer" }
